# Pinning our toolchain ensures ./scripts/regenerate_test_rustdocs.sh always
# emits the desired format.

[toolchain]
# Temporarily pin to version 43 while I am testing changes. 
channel = "nightly-2025-03-29"
